spring:
  server:
    servlet:
      session:
        cookie:
          same-site: none
          secure: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
#            scope:
#              - profile
#              - email
#            redirect-uri: "https://reposphere-vz6f.onrender.com/login/oauth2/code/google"
    name: rep
  servlet:
    multipart:
      # Max file size for a single file (e.g., 10MB)
      max-file-size: 100MB
      # Max total request size for the entire form (e.g., 10MB)
      max-request-size: 200MB
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: ${PORT:8082}
  forward-headers-strategy: framework
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto

CLOUDINARY_NAME: ${CLOUDINARY_NAME}
CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}