spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            scope:
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
  application:
    name: rep
  servlet:
    multipart:
      # Max file size for a single file (e.g., 10MB)
      max-file-size: 100MB
      # Max total request size for the entire form (e.g., 10MB)
      max-request-size: 200MB
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: ${PORT:8080}

CLOUDINARY_NAME: ${CLOUDINARY_NAME}
CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}